services:
  - type: web
    name: space-scraper
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: SLACK_BOT_TOKEN
        fromEnvVar: SLACK_BOT_TOKEN
